FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system libraries for audio support (torchaudio needs libsndfile1)
RUN apt-get update && apt-get --yes install libsndfile1

# Copy and install Python packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt