# FROM python:3.12-slim

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /tmp/

# RUN pip install --upgrade pip \
#     && pip install -r /tmp/requirements.txt \
#     && python -m spacy download en_core_web_sm

# FROM python:3.12-slim

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /tmp/
# RUN pip install --upgrade pip \
#     && pip install -r /tmp/requirements.txt \
#     && python -m spacy download en_core_web_sm

# WORKDIR /algo


# FROM username/app:latest

# # 安装额外依赖
# RUN pip install some-package

# # 复制你自己的代码
# COPY ./my_code /app/my_code

# # 修改入口
# CMD ["python", "/app/my_code/main.py"]


FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt stopwords && \
    python -m spacy download en_core_web_sm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

CMD ["python"]
